import { pgTable, text, integer, boolean, jsonb, timestamp, date, primaryKey } from "drizzle-orm/pg-core";
// SQL migration supplies cross-domain foreign keys and immutable-publication trigger.
export const questionCategories = pgTable("q_categories", { id: text("id").primaryKey(), title: text("title").notNull() });
export const questionVersions = pgTable("q_questions", {
 id: text("id").primaryKey(), categoryId: text("category_id").notNull(), prompt: text("prompt").notNull(),
 options: jsonb("options").notNull(), position: integer("position").notNull(), sensitive: boolean("sensitive").notNull().default(false), published: boolean("published").notNull().default(true),
});
export const questionnaireState = pgTable("q_state", { userId: text("user_id").primaryKey(), enrolled: boolean("enrolled").notNull().default(false), revision: integer("revision").notNull().default(0), birthDate: date("birth_date"), preferences: jsonb("preferences"), skipped: jsonb("skipped").notNull().default([]), updatedAt: timestamp("updated_at",{withTimezone:true}).notNull().defaultNow() });
export const questionAnswers = pgTable("q_answers", {userId:text("user_id").notNull(),questionId:text("question_id").notNull(),answerId:text("answer_id").notNull(),acceptable:jsonb("acceptable").notNull(),weight:integer("weight").notNull(),public:boolean("public").notNull().default(false),explanation:text("explanation").notNull().default(""),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[primaryKey({columns:[t.userId,t.questionId]})]);
export const questionnaireDecisions = pgTable("q_decisions", {actorId:text("actor_id").notNull(),targetId:text("target_id").notNull(),decision:text("decision").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[primaryKey({columns:[t.actorId,t.targetId]})]);
export const questionnaireConnections = pgTable("q_connections", {userA:text("user_a").notNull(),userB:text("user_b").notNull(),matchId:text("match_id").notNull().unique(),origin:text("origin").notNull().default("questionnaire"),status:text("status").notNull().default("active"),createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow()},t=>[primaryKey({columns:[t.userA,t.userB]})]);
export const questionnaireCache = pgTable("q_cache", {userA:text("user_a").notNull(),userB:text("user_b").notNull(),revisionA:integer("revision_a").notNull(),revisionB:integer("revision_b").notNull(),algorithm:text("algorithm").notNull(),result:jsonb("result").notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow()},t=>[primaryKey({columns:[t.userA,t.userB]})]);
