import React,{useState} from 'react';
import { FlatList,View,TextInput,Text,KeyboardAvoidingView,Platform } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams,useRouter } from 'expo-router';
import { useChat } from '@/hooks/use-chat';
import { useTheme } from '@/hooks/use-theme';
import { useQuestionnaireMutation } from '@/lib/questionnaire';
import { Action,Copy,Feedback,Loading } from '@/components/questionnaire/ui';
export default function Chat(){const {matchId}=useLocalSearchParams<{matchId:string}>(),router=useRouter(),{colors}=useTheme(),chat=useChat(matchId),unmatch=useQuestionnaireMutation('unmatch'),[draft,setDraft]=useState(''),[error,setError]=useState<unknown>(null);return <SafeAreaView style={{flex:1,backgroundColor:colors.background}}><KeyboardAvoidingView style={{flex:1,padding:16,gap:12}} behavior={Platform.OS==='ios'?'padding':undefined}><Action label="Back to messages" onPress={()=>router.replace('/dating/messages' as never)}/><Copy>Conversation</Copy>{chat.isInitialLoading&&<Loading/>}<Feedback error={chat.isAccessDenied?new Error('This conversation is no longer available.'):chat.error||error||unmatch.error}/>{chat.isError&&<Action label="Try again" onPress={()=>chat.refetch()}/>}<FlatList data={chat.messages} keyExtractor={m=>m.id} contentContainerStyle={{gap:12}} ListHeaderComponent={chat.hasMoreMessages?<Action label="Load earlier messages" onPress={()=>{void chat.loadOlderMessages();}}/>:null} renderItem={({item})=><View style={{padding:12,borderRadius:12,backgroundColor:item.senderId===chat.currentUserId?colors.secondary:colors.card,alignSelf:item.senderId===chat.currentUserId?'flex-end':'flex-start',maxWidth:'90%'}}><Text style={{color:colors.foreground,fontSize:16}}>{item.content}</Text><Text style={{color:colors.mutedForeground,fontSize:13}}>{new Date(item.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}{item.senderId===chat.currentUserId?` · ${item.status}`:''}</Text></View>}/><TextInput accessibilityLabel="Message" placeholder="Write a message" placeholderTextColor={colors.mutedForeground} multiline value={draft} onChangeText={setDraft} maxLength={2000} style={{minHeight:48,maxHeight:150,padding:12,borderWidth:1,borderRadius:12,borderColor:colors.border,color:colors.foreground,fontSize:16}}/><Action label={chat.isSending?'Sending…':'Send'} selected disabled={!draft.trim()||chat.isSending||chat.isAccessDenied||!chat.canSend} onPress={()=>{setError(null);chat.sendMessage(draft.trim(),{onSuccess:()=>setDraft(''),onError:e=>setError(e)});}}/><Action label="Unmatch" disabled={unmatch.isPending} onPress={()=>{void unmatch.mutateAsync({matchId}).then(()=>router.replace('/dating/messages' as never)).catch(()=>{});}}/></KeyboardAvoidingView></SafeAreaView>;}
