import type {
    OpsHistoryPair,
    OpsLocation,
    OpsOnCallSession,
    OpsPendingPair,
    OpsScheduledPair,
} from "@/components/admin/ops/types";

function iso(offsetMinutes: number) {
    return new Date(Date.now() + offsetMinutes * 60_000).toISOString();
}

export const DEMO_LOCATIONS: OpsLocation[] = [
    {
        id: "demo-loc-1",
        name: "Java House",
        address: "Westlands, Nairobi",
        vibe: "coffee",
        notes: "Cozy upstairs seating. Usually quiet weekday afternoons.",
        isActive: true,
    },
    {
        id: "demo-loc-2",
        name: "Artcaffe Kilimani",
        address: "Yaya Centre, Kilimani",
        vibe: "coffee",
        notes: "Natural light, good wifi.",
        isActive: true,
    },
    {
        id: "demo-loc-3",
        name: "Karura Forest",
        address: "Limuru Rd, Nairobi",
        vibe: "walk",
        notes: "Meet at the main gate. KES 100 entry.",
        isActive: true,
    },
    {
        id: "demo-loc-4",
        name: "Mercado",
        address: "Westgate Mall, Westlands",
        vibe: "dinner",
        notes: "Rooftop vibe. Book ahead on Fridays.",
        isActive: true,
    },
    {
        id: "demo-loc-5",
        name: "Brew Bistro",
        address: "Ngong Rd, Nairobi",
        vibe: "hangout",
        notes: "Pool tables, live music weekends.",
        isActive: true,
    },
];

export const DEMO_ON_CALL: OpsOnCallSession[] = [
    {
        id: "demo-call-1",
        roomName: "strath-vibe-aisha-david",
        status: "active",
        userA: {
            id: "demo-u1",
            firstName: "Aisha",
            phone: "+254 712 345 678",
            email: "aisha.mwangi@strathmore.edu",
            location: "Madaraka, Nairobi",
        },
        userB: {
            id: "demo-u2",
            firstName: "David",
            phone: "+254 733 222 111",
            email: "david.kamau@strathmore.edu",
            location: "Karen, Nairobi",
        },
        scheduledAt: iso(-25),
        startedAt: iso(-2),
        endedAt: null,
        createdAt: iso(-30),
        dateMatchStatus: "pending_setup",
        callCompleted: false,
        user1Decision: null,
        user2Decision: null,
    },
    {
        id: "demo-call-2",
        roomName: "strath-vibe-njeri-brian",
        status: "scheduled",
        userA: {
            id: "demo-u3",
            firstName: "Njeri",
            phone: "+254 720 998 877",
            email: "njeri.wangari@strathmore.edu",
            location: "Kileleshwa, Nairobi",
        },
        userB: {
            id: "demo-u4",
            firstName: "Brian",
            phone: null,
            email: "brian.otieno@strathmore.edu",
            location: "Lavington, Nairobi",
        },
        scheduledAt: iso(15),
        startedAt: null,
        endedAt: null,
        createdAt: iso(-10),
        dateMatchStatus: "pending_setup",
        callCompleted: false,
        user1Decision: null,
        user2Decision: null,
    },
    {
        id: "demo-call-3",
        roomName: "strath-vibe-cheruto-ian",
        status: "pending",
        userA: {
            id: "demo-u5",
            firstName: "Cheruto",
            phone: "+254 701 456 123",
            email: "cheruto.lagat@strathmore.edu",
            location: "South C, Nairobi",
        },
        userB: {
            id: "demo-u6",
            firstName: "Ian",
            phone: "+254 790 111 222",
            email: null,
            location: "Langata, Nairobi",
        },
        scheduledAt: null,
        startedAt: null,
        endedAt: null,
        createdAt: iso(-5),
        dateMatchStatus: "pending_setup",
        callCompleted: false,
        user1Decision: null,
        user2Decision: null,
    },
];

export const DEMO_PENDING_DATES: OpsPendingPair[] = [
    {
        id: "demo-pending-1",
        vibe: "coffee",
        createdAt: iso(-120),
        userA: {
            id: "demo-p1a",
            firstName: "Wanjiku",
            phone: "+254 722 555 444",
            email: "wanjiku.mwangi@strathmore.edu",
            location: "Ngong Road, Nairobi",
        },
        userB: {
            id: "demo-p1b",
            firstName: "Kevin",
            phone: "+254 733 666 777",
            email: "kevin.ochieng@strathmore.edu",
            location: "Parklands, Nairobi",
        },
    },
    {
        id: "demo-pending-2",
        vibe: "dinner",
        createdAt: iso(-240),
        userA: {
            id: "demo-p2a",
            firstName: "Amina",
            phone: "+254 711 333 222",
            email: "amina.hassan@strathmore.edu",
            location: "Kilimani, Nairobi",
        },
        userB: {
            id: "demo-p2b",
            firstName: "Tony",
            phone: null,
            email: "tony.kariuki@strathmore.edu",
            location: "Westlands, Nairobi",
        },
    },
    {
        id: "demo-pending-3",
        vibe: "walk",
        createdAt: iso(-60),
        userA: {
            id: "demo-p3a",
            firstName: "Zawadi",
            phone: "+254 708 111 999",
            email: null,
            location: "Lavington, Nairobi",
        },
        userB: {
            id: "demo-p3b",
            firstName: "Mark",
            phone: "+254 798 876 543",
            email: "mark.njoroge@strathmore.edu",
            location: "Runda, Nairobi",
        },
    },
    {
        id: "demo-pending-4",
        vibe: "hangout",
        createdAt: iso(-30),
        userA: {
            id: "demo-p4a",
            firstName: "Stacy",
            phone: "+254 715 222 888",
            email: "stacy.wambui@strathmore.edu",
            location: "Kileleshwa, Nairobi",
        },
        userB: {
            id: "demo-p4b",
            firstName: "Derrick",
            phone: "+254 734 000 111",
            email: "derrick.maina@strathmore.edu",
            location: "Hurlingham, Nairobi",
        },
    },
];

export const DEMO_SCHEDULED_DATES: OpsScheduledPair[] = [
    {
        id: "demo-sched-1",
        vibe: "coffee",
        createdAt: iso(-1440),
        scheduledAt: iso(150),
        venueName: "Java House",
        venueAddress: "Westlands, Nairobi",
        status: "scheduled",
        feedbackCount: 0,
        avgRating: null,
        userA: {
            id: "demo-s1a",
            firstName: "Makena",
            phone: "+254 722 111 000",
            email: "makena.muthoni@strathmore.edu",
            location: "Kilimani, Nairobi",
        },
        userB: {
            id: "demo-s1b",
            firstName: "Ryan",
            phone: "+254 733 444 555",
            email: "ryan.odhiambo@strathmore.edu",
            location: "Westlands, Nairobi",
        },
    },
    {
        id: "demo-sched-2",
        vibe: "dinner",
        createdAt: iso(-2880),
        scheduledAt: iso(60 * 26),
        venueName: "Mercado",
        venueAddress: "Westgate Mall, Westlands",
        status: "scheduled",
        feedbackCount: 0,
        avgRating: null,
        userA: {
            id: "demo-s2a",
            firstName: "Leila",
            phone: "+254 720 333 222",
            email: "leila.abdi@strathmore.edu",
            location: "Parklands, Nairobi",
        },
        userB: {
            id: "demo-s2b",
            firstName: "Jordan",
            phone: "+254 711 555 666",
            email: "jordan.kiprop@strathmore.edu",
            location: "Karen, Nairobi",
        },
    },
    {
        id: "demo-sched-3",
        vibe: "walk",
        createdAt: iso(-60 * 12),
        scheduledAt: iso(60 * 50),
        venueName: "Karura Forest",
        venueAddress: "Limuru Rd, Nairobi",
        status: "scheduled",
        feedbackCount: 0,
        avgRating: null,
        userA: {
            id: "demo-s3a",
            firstName: "Tasha",
            phone: "+254 701 777 666",
            email: "tasha.nyambura@strathmore.edu",
            location: "South C, Nairobi",
        },
        userB: {
            id: "demo-s3b",
            firstName: "Owen",
            phone: null,
            email: "owen.mutiso@strathmore.edu",
            location: "Lavington, Nairobi",
        },
    },
];

export const DEMO_HISTORY: OpsHistoryPair[] = [
    {
        id: "demo-hist-1",
        vibe: "coffee",
        createdAt: iso(-60 * 72),
        scheduledAt: iso(-60 * 24),
        venueName: "Artcaffe Kilimani",
        venueAddress: "Yaya Centre, Kilimani",
        status: "attended",
        feedbackCount: 2,
        avgRating: 4.5,
        userA: {
            id: "demo-h1a",
            firstName: "Priya",
            phone: "+254 722 888 777",
            email: "priya.patel@strathmore.edu",
            location: "Parklands, Nairobi",
        },
        userB: {
            id: "demo-h1b",
            firstName: "Sam",
            phone: "+254 733 111 222",
            email: "sam.mwenda@strathmore.edu",
            location: "Westlands, Nairobi",
        },
    },
    {
        id: "demo-hist-2",
        vibe: "dinner",
        createdAt: iso(-60 * 96),
        scheduledAt: iso(-60 * 72),
        venueName: "Mercado",
        venueAddress: "Westgate Mall, Westlands",
        status: "attended",
        feedbackCount: 1,
        avgRating: 5,
        userA: {
            id: "demo-h2a",
            firstName: "Nia",
            phone: "+254 720 555 111",
            email: "nia.ochanda@strathmore.edu",
            location: "Kilimani, Nairobi",
        },
        userB: {
            id: "demo-h2b",
            firstName: "Eddy",
            phone: "+254 711 444 888",
            email: "eddy.makokha@strathmore.edu",
            location: "Hurlingham, Nairobi",
        },
    },
    {
        id: "demo-hist-3",
        vibe: "walk",
        createdAt: iso(-60 * 120),
        scheduledAt: iso(-60 * 96),
        venueName: "Karura Forest",
        venueAddress: "Limuru Rd, Nairobi",
        status: "cancelled",
        feedbackCount: 0,
        avgRating: null,
        userA: {
            id: "demo-h3a",
            firstName: "Ruth",
            phone: "+254 701 222 333",
            email: "ruth.njoki@strathmore.edu",
            location: "Kileleshwa, Nairobi",
        },
        userB: {
            id: "demo-h3b",
            firstName: "Victor",
            phone: "+254 734 555 444",
            email: "victor.kibet@strathmore.edu",
            location: "Langata, Nairobi",
        },
    },
    {
        id: "demo-hist-4",
        vibe: "hangout",
        createdAt: iso(-60 * 144),
        scheduledAt: iso(-60 * 120),
        venueName: "Brew Bistro",
        venueAddress: "Ngong Rd, Nairobi",
        status: "no_show",
        feedbackCount: 1,
        avgRating: 2,
        userA: {
            id: "demo-h4a",
            firstName: "Cynthia",
            phone: "+254 722 666 555",
            email: "cynthia.wairimu@strathmore.edu",
            location: "South B, Nairobi",
        },
        userB: {
            id: "demo-h4b",
            firstName: "Alex",
            phone: null,
            email: "alex.kimani@strathmore.edu",
            location: "Lavington, Nairobi",
        },
    },
    {
        id: "demo-hist-5",
        vibe: "coffee",
        createdAt: iso(-60 * 168),
        scheduledAt: iso(-60 * 144),
        venueName: "Java House",
        venueAddress: "Westlands, Nairobi",
        status: "attended",
        feedbackCount: 2,
        avgRating: 3.5,
        userA: {
            id: "demo-h5a",
            firstName: "Mercy",
            phone: "+254 733 333 999",
            email: "mercy.achieng@strathmore.edu",
            location: "Parklands, Nairobi",
        },
        userB: {
            id: "demo-h5b",
            firstName: "Mo",
            phone: "+254 711 000 999",
            email: "mohamed.ali@strathmore.edu",
            location: "Eastleigh, Nairobi",
        },
    },
];
