import React,{useEffect,useState} from 'react';
import { View,Switch } from 'react-native';
import * as SecureStore from 'expo-secure-store';
import { useRouter } from 'expo-router';
import { useIdentity,useQuestionnaire,useQuestionnaireMutation,type Question,type State } from '@/lib/questionnaire';
import { Page,Copy,Action,Field,Feedback,Loading } from '@/components/questionnaire/ui';
type Payload={questions:Question[];state:State};
export default function Questions(){
 const q=useQuestionnaire<Payload>('questions'),router=useRouter(),[selected,setSelected]=useState<string|null>(null),[manage,setManage]=useState(false),[includeSkipped,setIncludeSkipped]=useState(false);
 const next=q.data?.questions.find(x=>!x.answer_id&&(includeSkipped||!q.data.state.skipped.includes(x.id)));
 const current=q.data?.questions.find(x=>x.id===selected)??next;
 return <Page title="What matters to you" back><Copy>Your answers help calculate compatibility. They stay private unless you publish them. Private answers still contribute to the overall percentage.</Copy>{q.isPending&&<Loading/>}<Feedback error={q.error}/>{q.isError&&<Action label="Try again" onPress={()=>q.refetch()}/>} {q.data&&<><Copy>{q.data.state.count} answered · {Math.min(20,q.data.state.count)} of 20 to start discovering</Copy>{q.data.state.complete&&<Action label="Discover people" selected onPress={()=>router.replace('/dating' as never)}/>}<Action label={manage?'Continue answering':'Review your answers'} onPress={()=>setManage(x=>!x)}/>{manage?q.data.questions.filter(x=>x.answer_id).map(x=><Action key={x.id} label={x.prompt} onPress={()=>{setSelected(x.id);setManage(false);}}/>):current?<Editor key={current.id} question={current} revision={q.data.state.revision} onDone={async()=>{await q.refetch();setSelected(null);}}/>:<><Copy>{q.data.state.count===q.data.questions.length?'You have answered every available question. You can review or update them any time.':'You have reached the end of this batch. Revisit skipped questions whenever you are ready.'}</Copy><Action label="Revisit skipped questions" onPress={()=>setIncludeSkipped(true)}/></>}</>}</Page>;
}
function Editor({question:q,revision,onDone}:{question:Question;revision:number;onDone:()=>Promise<void>}){
 const identity=useIdentity(),save=useQuestionnaireMutation('answers','PUT'),remove=useQuestionnaireMutation('answers','DELETE'),skip=useQuestionnaireMutation('skip');
 const [answer,setAnswer]=useState(q.answer_id??''),[acceptable,setAcceptable]=useState<string[]>(q.acceptable??[]),[weight,setWeight]=useState(q.weight??10),[visible,setVisible]=useState(q.public??false),[explanation,setExplanation]=useState(q.explanation??''),[loaded,setLoaded]=useState(false),[localError,setLocalError]=useState<unknown>(null);
 const key=`question-draft-${identity.data}-${q.id.replace(':','-')}`;
 useEffect(()=>{let active=true;void SecureStore.getItemAsync(key).then(raw=>{if(raw&&active){try{const d=JSON.parse(raw);if(d.revision===revision){setAnswer(d.answer);setAcceptable(d.acceptable);setWeight(d.weight);setVisible(d.visible);setExplanation(d.explanation);}}catch{ /* Invalid local draft; saved server answers remain available. */ }}}).catch(()=>{}).finally(()=>{if(active)setLoaded(true);});return()=>{active=false;};},[key]);
 useEffect(()=>{if(!loaded)return;const timer=setTimeout(()=>{void SecureStore.setItemAsync(key,JSON.stringify({revision,answer,acceptable,weight,visible,explanation})).catch(()=>{});},250);return()=>clearTimeout(timer);},[loaded,key,revision,answer,acceptable,weight,visible,explanation]);
 const busy=save.isPending||remove.isPending||skip.isPending;
 async function submit(){try{setLocalError(null);await save.mutateAsync({questionId:q.id,answerId:answer,acceptable,weight,public:visible,explanation,revision});await SecureStore.deleteItemAsync(key).catch(()=>{});await onDone();}catch(e){setLocalError(e);}}
 return <View style={{gap:12}}><Copy>{q.prompt}</Copy>{q.sensitive&&<Copy>This question is optional. Skip it if you prefer.</Copy>}<Copy>Your answer</Copy>{q.options.map(o=><Action key={o.id} label={o.label} selected={answer===o.id} disabled={busy||!loaded} onPress={()=>setAnswer(o.id)}/>)}<Copy>Answers you would accept from a partner</Copy>{q.options.map(o=><Action key={o.id} label={o.label} selected={acceptable.includes(o.id)} disabled={busy||!loaded} onPress={()=>setAcceptable(a=>a.includes(o.id)?a.filter(x=>x!==o.id):[...a,o.id])}/>)}<Copy>How important is this?</Copy>{[[0,'Not important'],[1,'A little important'],[10,'Somewhat important'],[50,'Very important'],[250,'Extremely important']].map(([value,label])=><Action key={value} label={String(label)} selected={weight===value} disabled={busy||!loaded} onPress={()=>setWeight(Number(value))}/>)}<Copy>Publish this answer for people who have also answered publicly</Copy><Switch accessibilityLabel="Publish this answer" value={visible} disabled={busy||!loaded} onValueChange={setVisible}/><Field label="Optional explanation" value={explanation} onChangeText={setExplanation} multiline/><Feedback error={localError||remove.error||skip.error}/><Action label={save.isPending?'Saving…':'Save and continue'} selected disabled={busy||!loaded||!answer||!acceptable.length} onPress={()=>{void submit();}}/><Action label="Skip this question" disabled={busy} onPress={()=>{void skip.mutateAsync({questionId:q.id}).then(onDone).catch(()=>{});}}/>{q.answer_id&&<Action label="Delete this answer" disabled={busy} onPress={()=>{void remove.mutateAsync({questionId:q.id,revision}).then(onDone).catch(()=>{});}}/>}</View>;
}
