import React from 'react';
import { ScrollView, View, Text, Pressable, TextInput, Image, ActivityIndicator, KeyboardAvoidingView, Platform } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTheme } from '@/hooks/use-theme';
import { useRouter } from 'expo-router';
import { compatibilityLabel, type Person } from '@/lib/questionnaire';
export function Page({title,children,back=false}:{title:string;children:React.ReactNode;back?:boolean}){
 const {colors}=useTheme(),router=useRouter();return <SafeAreaView style={{flex:1,backgroundColor:colors.background}} edges={['top','left','right']}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:20,gap:16,paddingBottom:40}}>{back&&<Action label="Back" onPress={()=>router.canGoBack()?router.back():router.replace('/dating' as never)}/>}<Text accessibilityRole="header" style={{fontSize:28,fontWeight:'700',color:colors.foreground}}>{title}</Text>{children}</ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
export function Copy({children}:{children:React.ReactNode}){const {colors}=useTheme();return <Text style={{fontSize:16,lineHeight:24,color:colors.foreground}}>{children}</Text>;}
export function Action({label,onPress,disabled=false,selected=false}:{label:string;onPress:()=>void;disabled?:boolean;selected?:boolean}){const {colors}=useTheme();return <Pressable accessibilityRole="button" accessibilityState={{disabled,selected}} disabled={disabled} onPress={onPress} style={({pressed})=>({minHeight:48,padding:12,borderRadius:12,borderWidth:1,borderColor:selected?colors.primary:colors.border,backgroundColor:selected?colors.primary:colors.card,opacity:disabled?0.5:pressed?0.75:1,justifyContent:'center'})}><Text style={{fontSize:16,fontWeight:'600',color:selected?colors.primaryForeground:colors.foreground}}>{label}</Text></Pressable>;}
export function Field({label,value,onChangeText,multiline=false,keyboardType='default'}:{label:string;value:string;onChangeText:(s:string)=>void;multiline?:boolean;keyboardType?:'default'|'numeric'}){const {colors}=useTheme();return <View style={{gap:6}}><Copy>{label}</Copy><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} multiline={multiline} keyboardType={keyboardType} style={{minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:12,padding:12,color:colors.foreground,backgroundColor:colors.card,fontSize:16}}/></View>;}
export function Feedback({error}:{error:unknown}){const {colors}=useTheme();return error?<Text accessibilityRole="alert" style={{fontSize:16,color:colors.foreground}}>{error instanceof Error?error.message:'Unable to save. Please try again.'}</Text>:null;}
export function Loading(){const {colors}=useTheme();return <ActivityIndicator accessibilityLabel="Loading" color={colors.primary}/>;}
export function PersonCard({person}:{person:Person}){const {colors}=useTheme(),router=useRouter();return <Pressable accessibilityRole="button" accessibilityLabel={`View ${person.name}'s profile`} onPress={()=>router.push(`/compatibility/${person.id}` as never)} style={{gap:8,paddingBottom:20,borderBottomWidth:1,borderColor:colors.border}}>{person.photos[0]&&<Image accessibilityLabel={`${person.name}'s profile photo`} source={{uri:person.photos[0]}} style={{width:'100%',height:260,borderRadius:16}}/>}<Text style={{fontSize:22,fontWeight:'600',color:colors.foreground}}>{person.name}, {person.age}</Text><Copy>{person.city} · {person.intentions.join(', ')}</Copy>{person.compatibility&&<Copy>{compatibilityLabel(person.compatibility)}</Copy>}<Copy>{person.bio}</Copy></Pressable>;}
